name = "Plots"
author = ["Tom Breloff (@tbreloff)"]
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "1.38.14"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Showoff = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
JLFzf = "1019f520-868f-41f5-a6de-eb00f4b6a39c"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
UnitfulLatexify = "45397f5d-5981-4c77-b2b3-fc36d6e9b728"
RecipesPipeline = "01d81517-befc-4cb6-b9ec-a95719d0359c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
UnicodeFun = "1cfade01-22cf-5700-b092-accc4b62d6e1"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"

[extras]
PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Gaston = "4b11ee91-296f-5714-9832-002c20994614"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
FreeType = "b38be410-82b0-50bf-ab77-7b57e271db43"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
InspectDR = "d0351b0e-4b05-5898-87b3-e2a8edfddd1d"
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"

[compat]
Requires = "1"
Showoff = "0.3.1, 1"
GR = "0.69.5 - 0.72"
PlotlyKaleido = "1"
Gaston = "1"
FixedPointNumbers = "0.6 - 0.8"
JLFzf = "0.1"
PrecompileTools = "1"
PGFPlotsX = "1"
Unzip = "0.1 - 0.2"
PlotlyBase = "0.7 - 0.8"
PythonPlot = "1"
UnitfulLatexify = "1"
RecipesPipeline = "0.6.10"
LaTeXStrings = "1"
PlotUtils = "1"
JSON = "0.21, 1"
StatsBase = "0.33, 0.34"
HDF5 = "0.16"
RelocatableFolders = "0.3, 1"
Scratch = "1"
Latexify = "0.14 - 0.15, 0.16"
PGFPlots = "3"
PyPlot = "2"
Preferences = "1"
FFMPEG = "0.2 - 0.4"
Measures = "0.3"
julia = "1.6"
RecipesBase = "1.3.1"
UnicodeFun = "0.4"
UnicodePlots = "3.4"
PlotThemes = "2, 3"
Contour = "0.5 - 0.6"
PlotlyJS = "0.18"
InspectDR = "0.4"
Reexport = "0.2, 1"
NaNMath = "0.3, 1"

[weakdeps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"

[targets]
test = ["Aqua", "Colors", "Distributions", "FileIO", "FilePathsBase", "FreeType", "Gaston", "GeometryBasics", "Gtk", "ImageMagick", "Images", "InspectDR", "LibGit2", "OffsetArrays", "PGFPlotsX", "PlotlyJS", "PlotlyBase", "PyPlot", "PythonPlot", "PlotlyKaleido", "HDF5", "RDatasets", "SentinelArrays", "StableRNGs", "StaticArrays", "StatsPlots", "Test", "TestImages", "UnicodePlots", "Unitful", "VisualRegressionTests"]

[extensions]
FileIOExt = "FileIO"
UnitfulExt = "Unitful"
GeometryBasicsExt = "GeometryBasics"
IJuliaExt = "IJulia"
ImageInTerminalExt = "ImageInTerminal"
