name = "PlotThemes"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "3.3.0"

[deps]
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
PlotUtils = "1"
julia = "1"
