name = "RecipesPipeline"
uuid = "01d81517-befc-4cb6-b9ec-a95719d0359c"
authors = ["Michael Krabbe Borregaard <mkborregaard@snm.ku.dk>"]
version = "0.1.7"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
PlotUtils = "0.6.5, 1"
RecipesBase = "0.8, 1.0"
julia = "1"

[extras]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
MakieRecipes = "3c562d8e-4afa-4f1c-99bf-ad54af2b207f"
MarketData = "945b72a4-3b13-509d-9b46-1525bb5c06de"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
Phylo = "aea672f4-3940-5932-aa44-993d1c3ff149"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"

[targets]
test = ["Test", "AbstractPlotting", "CairoMakie", "OrdinaryDiffEq",
        "StochasticDiffEq", "DiffEqNoiseProcess",
        "MakieRecipes", "MarketData", "TimeSeries", "Phylo", "GraphRecipes"]
