name: format

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  pr:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install JuliaFormatter and format
        run: |
          julia -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter"))'
          julia -e 'using JuliaFormatter; [format(["src", "test"]) for _ in 1:2]'
          git diff --exit-code

      - name: Create Pull Request
        if: ${{ failure() }}
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Format .jl files [skip ci]"
          title: 'Automatic JuliaFormatter.jl run'
          branch: auto-juliaformatter-pr
          delete-branch: true
          labels: formatting, automated pr, no changelog

      - name: Check outputs
        if: ${{ failure() }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
